networks:
  app-network:
    driver: bridge

services:
  postgres:
    image: pgvector/pgvector:pg15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./.data/pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - app-network
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      start_period: 5s
      timeout: 5s
      retries: 5

